name: spilth.org
description: Personal site of Brian Kelly
url: http://spilth.org/
port: 4200
markdown: kramdown
kramdown:
    toc_levels: 1..2
permalink: pretty
exclude: [Rakefile, Gemfile, Gemfile.lock]
pygments: true
mini_magick:
    thumbnail:
        source: images/original
        destination: images/thumbnail
        resize: "140x140"
    small:
        source: images/original
        destination: images/small
        resize: "320x240"
    medium:
        source: images/original
        destination: images/medium
        resize: "640x480"

